preload = /home/ben/Pictures/25414787-pramie-und-elegant-lila-hintergrund-schwarz-und-violett-wellig-hintergrund-schon-gradient-ubergang-kostenlos-foto Kopie.jpg
wallpaper = eDP-1, /home/ben/Pictures/25414787-pramie-und-elegant-lila-hintergrund-schwarz-und-violett-wellig-hintergrund-schon-gradient-ubergang-kostenlos-foto Kopie.jpg
